version: "3"
services:
  uptime-shark:
    image: yellowtech/uptime-shark
    container_name: uptime-shark
    volumes:
      - ./db:/app/db
    environment:
      # # the telegram api key
      # - TELEGRAMKEY=telegram-bot-api-token
      # # your telegram chat id
      # - TELEGRAMCHAT=your-chat-id
      - APIPASSWORD=yoursupersecretpassword!@#%#@!
    ports:
      - 8080:8080
    restart: unless-stopped
